### ISSUE TITLE
No result output

### ISSUE THREAD

**Issue by zhixuqiu** [NedaTavakoli/VF#1]
Hi, I installed VF. When I run the example greedy_snp. Although there are no errors, there is no output file.
Below is my running process:
```shell
$ ~/software/installed_dir/VF/build/greedy_snp -a 1000 -d 100 -vcf 1KG_chrMT.vcf -chr MT
INFO, VF::parseandSave, alpha = 1000
INFO, VF::parseandSave, delta = 100
INFO, VF::parseandSave, vcf file = 1KG_chrMT.vcf
INFO, VF::parseandSave, chromosome id = MT
INFO, VF::main, extracting SNPs from vcf file using command = /home/qiuzx/software/installed_dir/VF/build/vcftools-0.1.16/bin/vcftools --vcf 1KG_chrMT.vcf --chr MT --counts --remove-indels --out .VF.25514.txt 2>/dev/null
INFO, VF::main, vcftools finished
INFO, VF::main, count of variant containing positions = 3771
INFO, VF::main, count of variants = 3963
INFO, VF::main, starting timer
INFO, VF::main, time taken by variant selection algorithm = 8.1787e-05 seconds
INFO, VF::main, count of variant containing positions retained = 2132
INFO, VF::main, count of variants retained = 2232
INFO, VF::printVariantGapStats, before: (min, mean, max) = (0, 3, 49)
INFO, VF::printVariantGapStats, after: (min, mean, max) = (0, 6, 814)

$ ls
1KG_chrMT.vcf  README.md
```

**Comment by cjain7** [comment]
Hi,
The final buffer containing set of retained variants is not written out to console or file. This needs to be implemented. Did you try editing the code so far?

**Comment by zhixuqiu** [comment]
> Hi, The final buffer containing set of retained variants is not written out to console or file. This needs to be implemented. Did you try editing the code so far?

**Comment by zhixuqiu** [comment]
> Hi, The final buffer containing set of retained variants is not written out to console or file. This needs to be implemented. Did you try editing the code so far?

Yes, I tried it. However, the output VCF file has only the header line and no variant line.
```shell
$ ~/software/installed_dir/VF/build/greedy_snp -a 1000 -d 100 -vcf 1KG_chrMT.vcf -chr MT -prefix example
NFO, VF::parseandSave, alpha = 1000
INFO, VF::parseandSave, delta = 100
INFO, VF::parseandSave, vcf file = 1KG_chrMT.vcf
INFO, VF::parseandSave, chromosome id = MT
INFO, VF::parseandSave, prefix = example
INFO, VF::main, extracting SNPs from vcf file using command = /home/qiuzx/software/installed_dir/VF/build/vcftools-0.1.16/bin/vcftools --vcf 1KG_chrMT.vcf --chr MT --counts --remove-indels --out .VF.93710.txt 2>/dev/null
INFO, VF::main, vcftools finished
INFO, VF::main, count of variant containing positions = 3771
INFO, VF::main, count of variants = 3963
INFO, VF::main, starting timer
INFO, VF::main, time taken by variant selection algorithm = 4.5942e-05 seconds
INFO, VF::main, count of variant containing positions retained = 2132
INFO, VF::main, count of variants retained = 2232
INFO, VF::printVariantGapStats, before: (min, mean, max) = (0, 3, 49)
INFO, VF::printVariantGapStats, after: (min, mean, max) = (0, 6, 814)
INFO, VF::print_snp_vcf, written retained variant loci to .VF.10389.txt
cat 1KG_chrMT.vcf | grep '^#' > example.inputrecords.vcf
cat 1KG_chrMT.vcf | grep -vE '^#' | grep 'SNP' | awk -v chr=MT '$1 == chr {print $0}' >> example.inputrecords.vcf
cat example.inputrecords.vcf | grep '^#' > example.retainedrecords.vcf
cat example.inputrecords.vcf | grep -vE '^#' > .VF.58596.txt
awk 'NR == FNR { a[$0]; next } $2 in a' .VF.10389.txt .VF.58596.txt >> example.retainedrecords.vcf
rm -f .VF.10389.txt*
rm -f .VF.58596.txt*

$ ls
1KG_chrMT.vcf  example.inputrecords.vcf  example.retainedrecords.vcf
$ bcftools view -h example.retainedrecords.vcf|head -n 3
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=20151002

$ bcftools view -H example.retainedrecords.vcf|wc
    0       0       0
```

**Comment by cjain7** [comment]
Ok, I will take a look at this issue this weekend.

**Comment by NedaTavakoli** [comment]
> > Hi, The final buffer containing set of retained variants is not written out to console or file. This needs to be implemented. Did you try editing the code so far?
> 
> Yes, I tried it. However, the output VCF file has only the header line and no variant line.
> 
> ```shell
> $ ~/software/installed_dir/VF/build/greedy_snp -a 1000 -d 100 -vcf 1KG_chrMT.vcf -chr MT -prefix example
> NFO, VF::parseandSave, alpha = 1000
> INFO, VF::parseandSave, delta = 100
> INFO, VF::parseandSave, vcf file = 1KG_chrMT.vcf
> INFO, VF::parseandSave, chromosome id = MT
> INFO, VF::parseandSave, prefix = example
> INFO, VF::main, extracting SNPs from vcf file using command = /home/qiuzx/software/installed_dir/VF/build/vcftools-0.1.16/bin/vcftools --vcf 1KG_chrMT.vcf --chr MT --counts --remove-indels --out .VF.93710.txt 2>/dev/null
> INFO, VF::main, vcftools finished
> INFO, VF::main, count of variant containing positions = 3771
> INFO, VF::main, count of variants = 3963
> INFO, VF::main, starting timer
> INFO, VF::main, time taken by variant selection algorithm = 4.5942e-05 seconds
> INFO, VF::main, count of variant containing positions retained = 2132
> INFO, VF::main, count of variants retained = 2232
> INFO, VF::printVariantGapStats, before: (min, mean, max) = (0, 3, 49)
> INFO, VF::printVariantGapStats, after: (min, mean, max) = (0, 6, 814)
> INFO, VF::print_snp_vcf, written retained variant loci to .VF.10389.txt
> cat 1KG_chrMT.vcf | grep '^#' > example.inputrecords.vcf
> cat 1KG_chrMT.vcf | grep -vE '^#' | grep 'SNP' | awk -v chr=MT '$1 == chr {print $0}' >> example.inputrecords.vcf
> cat example.inputrecords.vcf | grep '^#' > example.retainedrecords.vcf
> cat example.inputrecords.vcf | grep -vE '^#' > .VF.58596.txt
> awk 'NR == FNR { a[$0]; next } $2 in a' .VF.10389.txt .VF.58596.txt >> example.retainedrecords.vcf
> rm -f .VF.10389.txt*
> rm -f .VF.58596.txt*
> 
> $ ls
> 1KG_chrMT.vcf  example.inputrecords.vcf  example.retainedrecords.vcf
> $ bcftools view -h example.retainedrecords.vcf|head -n 3
> ##fileformat=VCFv4.2
> ##FILTER=<ID=PASS,Description="All filters passed">
> ##fileDate=20151002
> 
> $ bcftools view -H example.retainedrecords.vcf|wc
>   0       0           0
> ```

**Comment by NedaTavakoli** [comment]
The problem is fixed now. Thanks for raising this issue. 
 Now, you should see the following results (for the example that you wanted to run):
`
$ bcftools view -H example.retainedrecords.vcf|wc
`
`   2142 5424248 10902375
`
